name: Sync From Faraday

on:
  workflow_dispatch:
  schedule:
    - cron: '18 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Clone/Copy Remote
      run: |-
        git clone https://github.com/infobyte/faraday.git faraday-src/
        rsync -a --exclude={'Dockerfile','.gitlab','.git','.gitignore','.github'} faraday-src/ ./
        rm -rf faraday-src/

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Sync faraday: ${timestamp}" || exit 0
        git push
